# Agenda

1. Intro to Jupyter
2. NumPy
    - Array 
    - dtypes
    - Boolean indexing
    - Broadcasting
3. Pandas
    - Series and data frames
    - Setting and retrieving
    - Filtering 
    - String data
    - Times and dates
    - Sorting
    - Grouping
    - Pivot tables
    - Optimization
    - Plotting (esp with Seaborn)

In [1]:
print('Hello!')

Hello!


In [4]:
x = 102

In [5]:
print(x)

102


# Two modes

- Edit mode -- when I type, the text is placed in the cell. Click in the cell or press ENTER for edit mode. Green outline in edit mode.
- Command mode -- anything I type is treated as a Jupyter command. Click to the left of the cell or press ESC for command mode.  Blue outline in command mode.

Commands in command mode:
- `c` -- copy the cell
- `x` -- cut the cell
- `v` -- paste the cell
- `h` -- help, what keys do what?
- `a` -- create a new cell *above* the current one
- `b` -- create a new cell *below* the current one
- `y` -- turn a cell into a code cell
- `m` -- turn a cell into Markdown documentation

Shift+ENTER = execute the cell

In [1]:
print('Hello')

Hello


# Magic commands

All magic commands start with `%`.

In [7]:
%ls

'Apple - 2023-06June-01.ipynb'


In [8]:
%ls /etc/

6to4.conf.applesaved		       ntp.conf.applesaved
AFP.conf			       ntp_opendirectory.conf
CiscoSystemsVPNClient@		       openldap/
X11@				       openssl/
afpovertcp.cfg			       opt/
afpovertcp.cfg~orig		       pam.d/
aliases@			       passwd
aliases.db			       passwd~orig
apache2/			       paths
asl/				       paths.d/
asl.conf			       paths~orig
authorization.deprecated	       pear.conf-previous
authorization.user_modified	       periodic/
auto_home			       pf.anchors/
auto_master			       pf.conf
auto_master~orig		       pf.os
autofs.conf			       php.ini.default-5.2-previous
bash_completion.d*		       php.ini.default-5.2-previous~orig
bashrc				       php.ini.default-previous
bashrc_Apple_Terminal		       php.ini.default-previous~orig
bashrc~previous			       postfix/
com.apple.screensharing.agent.launchd  postgres-reg.ini
crontab				       ppp/
crontab.applesaved		       printcap
csh.cshrc			       profile
csh.cshrc~orig			       profile~orig
csh.login			       protocols
csh.l

In [9]:
x = 100
y = [10, 20, 30]
z = {'a':10, 'b':20}

In [10]:
%whos

Variable   Type    Data/Info
----------------------------
x          int     100
y          list    n=3
z          dict    n=2


In [14]:
def hello(name):
    x += 1
    return f'Hello, {name}!'

In [15]:
hello('world')

UnboundLocalError: cannot access local variable 'x' where it is not associated with a value

In [16]:
%debug

> /var/folders/d9/v8tsklln4477fll05wkgcpth0000gn/T/ipykernel_36788/1902841121.py(2)hello()
      1 def hello(name):
----> 2     x += 1
      3     return f'Hello, {name}!'

ipdb> q


In [17]:
%magic

In [18]:
%autosave 30

Autosaving every 30 seconds


In [2]:
!ls /etc/

6to4.conf.applesaved		       ntp.conf.applesaved
AFP.conf			       ntp_opendirectory.conf
CiscoSystemsVPNClient		       openldap
X11				       openssl
afpovertcp.cfg			       opt
afpovertcp.cfg~orig		       pam.d
aliases				       passwd
aliases.db			       passwd~orig
apache2				       paths
asl				       paths.d
asl.conf			       paths~orig
authorization.deprecated	       pear.conf-previous
authorization.user_modified	       periodic
auto_home			       pf.anchors
auto_master			       pf.conf
auto_master~orig		       pf.os
autofs.conf			       php.ini.default-5.2-previous
bash_completion.d		       php.ini.default-5.2-previous~orig
bashrc				       php.ini.default-previous
bashrc_Apple_Terminal		       php.ini.default-previous~orig
bashrc~previous			       postfix
com.apple.screensharing.agent.launchd  postgres-reg.ini
crontab				       ppp
crontab.applesaved		       printcap
csh.cshrc			       profile
csh.cshrc~orig			       profile~orig
csh.login			       protocols
csh.login~orig			 

In [12]:
filenames = !ls

In [13]:
type(filenames)

IPython.utils.text.SList

In [14]:
filenames.get_paths()

[PosixPath('Apple - 2023-06June-01.ipynb')]

# NumPy

In [15]:
x = 1

In [16]:
import sys
sys.getsizeof(x)

28

In [17]:
x = 123414141414141341 ** 1000

In [18]:
sys.getsizeof(x)

7596

# NumPy

NumPy provides us with a data structure: NumPy ndarray -- n-dimensional array.

In [19]:
import numpy as np

In [20]:
# don't use np.ndarray!

a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
type(a)

numpy.ndarray

In [22]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
# can we try some list things?

a[0]

10

In [24]:
a[1]

20

In [25]:
a[-1]

90

In [26]:
a[-2]

80

In [27]:
# slice
a[4:7]

array([50, 60, 70])

In [28]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
mylist = [10, 20, 30]
mylist + mylist

[10, 20, 30, 10, 20, 30]

In [30]:
# add a NumPy array to another array
a + a

array([ 20,  40,  60,  80, 100, 120, 140, 160, 180])

In [31]:
b = np.array([100, 200])

a + b

ValueError: operands could not be broadcast together with shapes (9,) (2,) 

 # Another few ways to create arrays
 


In [32]:
# we could do this...
a = np.array(range(10, 20))
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
# ... but instead, we should do this:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
# get a bunch of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
# get a bunch of zeroes
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
# what about random numbers?
np.random.seed(0)
np.random.randint(0, 100, 5)   # 5 numbers from 0-100

array([44, 47, 64, 67, 67])

In [38]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the `~numpy.random.Generator.randint`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to

In [39]:
# what about random floats?

np.random.rand(10)   # how many numbers

array([0.84725174, 0.6235637 , 0.38438171, 0.29753461, 0.05671298,
       0.27265629, 0.47766512, 0.81216873, 0.47997717, 0.3927848 ])

In [40]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
# I want index 3
a[3]

13

In [42]:
# I want index 5
a[5]

15

In [44]:
# I want indexes 3 and 5 -- fancy indexing
a[ [3,5] ]

array([13, 15])

In [45]:
a [ [3,5,3,5] ]

array([13, 15, 13, 15])

In [46]:
b = a[[3,5]]

In [47]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [48]:
b

array([13, 15])

In [49]:
a[3,5]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

# Broadcasting

In [50]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
mylist

[10, 20, 30]

In [52]:
mylist + 40

TypeError: can only concatenate list (not "int") to list

In [53]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [54]:
a + 40

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [55]:
a += 40
a

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [56]:
a - 30

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [57]:
a * 10

array([500, 510, 520, 530, 540, 550, 560, 570, 580, 590])

In [58]:
a / 4

array([12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75, 14.  , 14.25, 14.5 ,
       14.75])

In [59]:
a // 4

array([12, 12, 13, 13, 13, 13, 14, 14, 14, 14])

In [60]:
a % 3

array([2, 0, 1, 2, 0, 1, 2, 0, 1, 2])

In [61]:
a ** 3

array([125000, 132651, 140608, 148877, 157464, 166375, 175616, 185193,
       195112, 205379])

In [62]:
a

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

# Exercises: NumPy basics

1. Define an array with every number from 567 to 890. What is the number at index 8 in this array?  
2. Now define the same array, but skipping by 3 for each number. (That is, 567 to 890, but with step size of 3.) Now what is the number at index 15?
3. What happens when we add 10 to each number? 
4. What happens when we put all these numbers to the 100th power?


In [64]:
a = np.arange(567, 890)
a[8]

575

In [65]:
a = np.arange(567, 890, 3)
a[15]

612

In [67]:
a + 10

array([577, 580, 583, 586, 589, 592, 595, 598, 601, 604, 607, 610, 613,
       616, 619, 622, 625, 628, 631, 634, 637, 640, 643, 646, 649, 652,
       655, 658, 661, 664, 667, 670, 673, 676, 679, 682, 685, 688, 691,
       694, 697, 700, 703, 706, 709, 712, 715, 718, 721, 724, 727, 730,
       733, 736, 739, 742, 745, 748, 751, 754, 757, 760, 763, 766, 769,
       772, 775, 778, 781, 784, 787, 790, 793, 796, 799, 802, 805, 808,
       811, 814, 817, 820, 823, 826, 829, 832, 835, 838, 841, 844, 847,
       850, 853, 856, 859, 862, 865, 868, 871, 874, 877, 880, 883, 886,
       889, 892, 895, 898])

In [68]:
a ** 100

array([-9020696473897379935,                    0,  4198723078203128017,
                          0,  6124479562928926417,                    0,
          58048846484851105,                    0, -2975346391895392575,
                          0,  7836038698588907825,                    0,
        7595481941288388977,                    0, -8700092710492043903,
                          0, -6307674051997439775,                    0,
        5859149131872887953,                    0, -6592530228025946351,
                          0,  3822435680105440353,                    0,
        8785443043703031297,                    0,  3684047930374716145,
                          0,  6418449141385932721,                    0,
        2382589516370802241,                    0, -2933335000278514143,
                          0,  -783686578179834799,                    0,
        8555592170996849489,                    0, -5215599266414998751,
                          0,  6255757699345897793, 

# Next up:

1. Methods
2. Broadcasting of conditions

Resume at 11:25

In [69]:
a = np.random.randint(-50, 50, 20)
a

array([-25,  27,  22, -41, -30,  30,  19,  29,  -3,  14,  32,  49,  38,
        -1, -21, -31, -31, -36, -11, -18])

In [71]:
a.size

20

In [72]:
a.min()

-41

In [73]:
a.max()

49

In [74]:
a.mean()

0.6

In [75]:
a.std()

28.011426240018555

In [78]:
a.max

<function ndarray.max>

In [79]:
x = a.max

In [80]:
x()

49

In [81]:
x = a.max()

In [82]:
x

49

In [83]:
x = a.max

In [84]:
x

<function ndarray.max>

In [85]:
x = a

# Mask arrays

In [87]:
a = np.random.randint(-50, 50, 6)
a

array([ 15, -41,   7, -18, -19,  24])

In [88]:
# fancy indexing
a[[2, 4]]

array([  7, -19])

In [89]:
# mask array -- only True and False
# must be of the same length!
a[[True, False, True, False, True, False]]

array([ 15,   7, -19])

# Broadcast and boolean arrays

In [90]:
a + 15

array([ 30, -26,  22,  -3,  -4,  39])

In [91]:
a == 7 

array([False, False,  True, False, False, False])

In [92]:
a[a==7]   # only elements of a that are 7

array([7])

In [93]:
a < 0

array([False,  True, False,  True,  True, False])

In [94]:
a[a<0]

array([-41, -18, -19])

In [97]:
# I want all numbers less than the mean

a[   a < a.mean()  ]

array([-41, -18, -19])

In [98]:
np.median(a)

-5.5

In [99]:
s = 'aBcD'

str.lower(s)

'abcd'

In [100]:
s.lower()

'abcd'

In [101]:
np.quantile(a, 0.5)

-5.5

In [102]:
np.median([10, 20,30])

20.0

# Exercise: Weather

1. Create a NumPy array with the expected high temperatures for the next 10 days.
2. Find the average temp.
3. Find all of the temps > than the average.
4. Find all of the temps > than the average + the standard deviation.

In [103]:
a = np.array([39, 28, 26, 26, 27, 28, 30, 31, 29, 28])
a

array([39, 28, 26, 26, 27, 28, 30, 31, 29, 28])

In [104]:
a.mean()

29.2

In [105]:
a.sum() / a.size

29.2

In [106]:
np.mean(a)

29.2

In [111]:
a[a > a.mean()]   

array([39, 30, 31])

In [113]:
a[a > a.mean() + a.std()]

array([39])

In [116]:
#  which indexes fit our criteria?
np.where(a > a.mean())

(array([0, 6, 7]),)

In [122]:
# let's find the odd numbers?

a[a % 2 == 1]

array([39, 27, 31, 29])

In [127]:
# what if I want numbers above the average that are *also* odd?


a > a.mean()   and  a % 2 == 1


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [130]:
s = input('Enter your name: ').strip()

if s:
    print(f'Hello, {s}!')
else:
    print('You did not give me a name!')

Enter your name: 
You did not give me a name!


In [133]:
# what if I want numbers above the average that are *also* odd?

# in Numpy, we can use:
# |  or
# &   and
# ~   not

a[(a > a.mean())   &
  (a % 2 == 1)]


array([39, 31])

# Exercises:

## subhed
### subsubhed

1. Create a NumPy array of 20 random ints from 0-1,000.
2. What is the smallest even number greater than the mean?
3. Show all numbers that are less than mean-std or greater than mean+std.

In [134]:
np.random.seed(0)
a = np.random.randint(0, 1000, 20)
a

array([684, 559, 629, 192, 835, 763, 707, 359,   9, 723, 277, 754, 804,
       599,  70, 472, 600, 396, 314, 705])

In [139]:
a[(a > a.mean()) & 
  (a % 2 == 0)].min()

600

In [143]:
a[(a > a.mean() + a.std()) | 
  (a < a.mean() - a.std())]

array([192, 835,   9, 277, 804,  70])

In [145]:
# random floats

np.random.rand(10) * 100

array([97.86183422, 79.91585642, 46.14793623, 78.05291763, 11.82744259,
       63.99210213, 14.33532874, 94.4668917 , 52.18483218, 41.466194  ])

In [ ]:
np.random.rand