# Agenda

1. `nan`
2. 2D arrays and shapes
3. sorting
4. Pandas

In [2]:
import numpy as np


In [3]:
a = np.array([10, 20, 30, 40, 50])
a.dtype

dtype('int64')

In [4]:
a[2] = 12.34
a

array([10, 20, 12, 40, 50])

In [5]:
a = np.array([10, 20, 30, 40, 50], dtype=np.float64)
a.dtype

dtype('float64')

In [6]:
a[2] = 12.34
a

array([10.  , 20.  , 12.34, 40.  , 50.  ])

In [12]:
a = np.array([10, 20, 30, 40, 50])
a.dtype

dtype('int64')

In [13]:
a[2] = '123'

In [14]:
a

array([ 10,  20, 123,  40,  50])

In [15]:
a.dtype

dtype('int64')

In [16]:
a[3] = 98.76
a.dtype

dtype('int64')

In [10]:
a[3] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

In [11]:
a.dtype

dtype('int64')

In [17]:
a = np.array('hello out there'.split())

In [18]:
a

array(['hello', 'out', 'there'], dtype='<U5')

In [19]:
a[0] = 'xyz'
a

array(['xyz', 'out', 'there'], dtype='<U5')

In [20]:
a[1] = 'hijklmnop'

In [21]:
a

array(['xyz', 'hijkl', 'there'], dtype='<U5')

In [23]:
a = a.astype('<U30')
a

array(['xyz', 'hijkl', 'there'], dtype='<U30')

In [24]:
a[1] = 'rstuvwxyz'
a

array(['xyz', 'rstuvwxyz', 'there'], dtype='<U30')

In [25]:
a = np.array([{'a':10, 'b':20}])

In [26]:
a

array([{'a': 10, 'b': 20}], dtype=object)

In [27]:
a = np.array([27, 26, 27, 26, 27])
a.mean()

26.6

In [28]:
# what if we have a problem getting a reading?
a = np.array([27, 26, 0, 26, 27])
a.mean()

21.2

# `nan` -- not a number

`nan` allows us to have numbers but know that they aren't accurate/real.

In [29]:
np.nan

nan

In [30]:
type(np.nan)

float

In [31]:
np.nan == 0

False

In [32]:
np.nan == np.nan

False

In [33]:
a = np.array([10, 20, 30, np.nan, 50, 60])
a

array([10., 20., 30., nan, 50., 60.])

In [34]:
a.dtype

dtype('float64')

In [35]:
a.mean()

nan

In [37]:
# option 1: find nan, remove it, and calculate with the rest
# this doesn't work...

a[a != np.nan].mean()

nan

In [38]:
# use np.isnan, which returns True for nan

np.isnan(a)

array([False, False, False,  True, False, False])

In [41]:
# use ~ to flip the logic
a[~np.isnan(a)].mean()

34.0

In [42]:
a = np.array([10, 20, 30])
a/0

/var/folders/d9/v8tsklln4477fll05wkgcpth0000gn/T/ipykernel_60061/3888640601.py:2: RuntimeWarning: divide by zero encountered in divide
  a/0


array([inf, inf, inf])

In [43]:
type(np.inf)

float

In [44]:
np.inf == np.inf

True

In [45]:
a

array([10, 20, 30])

In [46]:
a = np.array([10, 20, 30, np.nan, np.nan, 50, 60])
a

array([10., 20., 30., nan, nan, 50., 60.])

In [47]:
a.size

7

In [48]:
a.isnan()

AttributeError: 'numpy.ndarray' object has no attribute 'isnan'

In [49]:
np.isnan(a).sum()

2

In [50]:
np.count_nonzero(a)

7

In [51]:
a

array([10., 20., 30., nan, nan, 50., 60.])

In [54]:
# another technique: replace nan with something

a[np.isnan(a)] = 999

In [55]:
a

array([ 10.,  20.,  30., 999., 999.,  50.,  60.])

In [57]:
# similiar: replace nan with the mean

a = np.array([10., 20., 30., np.nan, np.nan, 50., 60.])

# Exercise: Working with `nan`

1. Define a NumPy array with 20 integers between 0-1,000.
2. Change all even numbers to `nan`.
3. Calculate the mean of the numbers that remained.
4. Replace all `nan` values with the non-na