# Agenda

1. `nan`
2. 2D arrays and shapes
3. sorting
4. Pandas

In [2]:
import numpy as np


In [3]:
a = np.array([10, 20, 30, 40, 50])
a.dtype

dtype('int64')

In [4]:
a[2] = 12.34
a

array([10, 20, 12, 40, 50])

In [5]:
a = np.array([10, 20, 30, 40, 50], dtype=np.float64)
a.dtype

dtype('float64')

In [6]:
a[2] = 12.34
a

array([10.  , 20.  , 12.34, 40.  , 50.  ])

In [12]:
a = np.array([10, 20, 30, 40, 50])
a.dtype

dtype('int64')

In [13]:
a[2] = '123'

In [14]:
a

array([ 10,  20, 123,  40,  50])

In [15]:
a.dtype

dtype('int64')

In [16]:
a[3] = 98.76
a.dtype

dtype('int64')

In [10]:
a[3] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

In [11]:
a.dtype

dtype('int64')

In [17]:
a = np.array('hello out there'.split())

In [18]:
a

array(['hello', 'out', 'there'], dtype='<U5')

In [19]:
a[0] = 'xyz'
a

array(['xyz', 'out', 'there'], dtype='<U5')

In [20]:
a[1] = 'hijklmnop'

In [21]:
a

array(['xyz', 'hijkl', 'there'], dtype='<U5')

In [23]:
a = a.astype('<U30')
a

array(['xyz', 'hijkl', 'there'], dtype='<U30')

In [24]:
a[1] = 'rstuvwxyz'
a

array(['xyz', 'rstuvwxyz', 'there'], dtype='<U30')

In [25]:
a = np.array([{'a':10, 'b':20}])

In [26]:
a

array([{'a': 10, 'b': 20}], dtype=object)

In [27]:
a = np.array([27, 26, 27, 26, 27])
a.mean()

26.6

In [28]:
# what if we have a problem getting a reading?
a = np.array([27, 26, 0, 26, 27])
a.mean()

21.2

# `nan` -- not a number

`nan` allows us to have numbers but know that they aren't accurate/real.

In [29]:
np.nan

nan

In [30]:
type(np.nan)

float

In [31]:
np.nan == 0

False

In [32]:
np.nan == np.nan

False

In [33]:
a = np.array([10, 20, 30, np.nan, 50, 60])
a

array([10., 20., 30., nan, 50., 60.])

In [34]:
a.dtype

dtype('float64')

In [35]:
a.mean()

nan

In [ ]:
# option 1: find nan, remove it, and calculate with the rest

a[a != np.nan]