# Agenda

1. `nan`
2. 2D arrays and shapes
3. sorting
4. Pandas

In [2]:
import numpy as np


In [3]:
a = np.array([10, 20, 30, 40, 50])
a.dtype

dtype('int64')

In [4]:
a[2] = 12.34
a

array([10, 20, 12, 40, 50])

In [5]:
a = np.array([10, 20, 30, 40, 50], dtype=np.float64)
a.dtype

dtype('float64')

In [6]:
a[2] = 12.34
a

array([10.  , 20.  , 12.34, 40.  , 50.  ])

In [7]:
a = np.array([10, 20, 30, 40, 50])
a.dtype

dtype('int64')

In [8]:
a[2] = '123'

In [9]:
a

array([ 10,  20, 123,  40,  50])

In [ ]:
a[3] = 'hel'