# Agenda

1. Intro to Jupyter
2. NumPy
    - Array 
    - dtypes
    - Boolean indexing
    - Broadcasting
3. Pandas
    - Series and data frames
    - Setting and retrieving
    - Filtering 
    - String data
    - Times and dates
    - Sorting
    - Grouping
    - Pivot tables
    - Optimization
    - Plotting (esp with Seaborn)

In [1]:
print('Hello!')

Hello!


In [4]:
x = 102

In [5]:
print(x)

102


# Two modes

- Edit mode -- when I type, the text is placed in the cell. Click in the cell or press ENTER for edit mode. Green outline in edit mode.
- Command mode -- anything I type is treated as a Jupyter command. Click to the left of the cell or press ESC for command mode.  Blue outline in command mode.

Commands in command mode:
- `c` -- copy the cell
- `x` -- cut the cell
- `v` -- paste the cell
- `h` -- help, what keys do what?
- `a` -- create a new cell *above* the current one
- `b` -- create a new cell *below* the current one
- `y` -- turn a cell into a code cell
- `m` -- turn a cell into Markdown documentation

Shift+ENTER = execute the cell

In [1]:
print('Hello')

Hello


# Magic commands

All magic commands start with `%`.

In [7]:
%ls

'Apple - 2023-06June-01.ipynb'


In [8]:
%ls /etc/

6to4.conf.applesaved		       ntp.conf.applesaved
AFP.conf			       ntp_opendirectory.conf
CiscoSystemsVPNClient@		       openldap/
X11@				       openssl/
afpovertcp.cfg			       opt/
afpovertcp.cfg~orig		       pam.d/
aliases@			       passwd
aliases.db			       passwd~orig
apache2/			       paths
asl/				       paths.d/
asl.conf			       paths~orig
authorization.deprecated	       pear.conf-previous
authorization.user_modified	       periodic/
auto_home			       pf.anchors/
auto_master			       pf.conf
auto_master~orig		       pf.os
autofs.conf			       php.ini.default-5.2-previous
bash_completion.d*		       php.ini.default-5.2-previous~orig
bashrc				       php.ini.default-previous
bashrc_Apple_Terminal		       php.ini.default-previous~orig
bashrc~previous			       postfix/
com.apple.screensharing.agent.launchd  postgres-reg.ini
crontab				       ppp/
crontab.applesaved		       printcap
csh.cshrc			       profile
csh.cshrc~orig			       profile~orig
csh.login			       protocols
csh.l

In [9]:
x = 100
y = [10, 20, 30]
z = {'a':10, 'b':20}

In [10]:
%whos

Variable   Type    Data/Info
----------------------------
x          int     100
y          list    n=3
z          dict    n=2


In [14]:
def hello(name):
    x += 1
    return f'Hello, {name}!'

In [15]:
hello('world')

UnboundLocalError: cannot access local variable 'x' where it is not associated with a value

In [16]:
%debug

> /var/folders/d9/v8tsklln4477fll05wkgcpth0000gn/T/ipykernel_36788/1902841121.py(2)hello()
      1 def hello(name):
----> 2     x += 1
      3     return f'Hello, {name}!'

ipdb> q


In [17]:
%magic

In [18]:
%autosave 30

Autosaving every 30 seconds


In [2]:
!ls /etc/

6to4.conf.applesaved		       ntp.conf.applesaved
AFP.conf			       ntp_opendirectory.conf
CiscoSystemsVPNClient		       openldap
X11				       openssl
afpovertcp.cfg			       opt
afpovertcp.cfg~orig		       pam.d
aliases				       passwd
aliases.db			       passwd~orig
apache2				       paths
asl				       paths.d
asl.conf			       paths~orig
authorization.deprecated	       pear.conf-previous
authorization.user_modified	       periodic
auto_home			       pf.anchors
auto_master			       pf.conf
auto_master~orig		       pf.os
autofs.conf			       php.ini.default-5.2-previous
bash_completion.d		       php.ini.default-5.2-previous~orig
bashrc				       php.ini.default-previous
bashrc_Apple_Terminal		       php.ini.default-previous~orig
bashrc~previous			       postfix
com.apple.screensharing.agent.launchd  postgres-reg.ini
crontab				       ppp
crontab.applesaved		       printcap
csh.cshrc			       profile
csh.cshrc~orig			       profile~orig
csh.login			       protocols
csh.login~orig			 

In [12]:
filenames = !ls

In [13]:
type(filenames)

IPython.utils.text.SList

In [14]:
filenames.get_paths()

[PosixPath('Apple - 2023-06June-01.ipynb')]

# NumPy

In [15]:
x = 1

In [16]:
import sys
sys.getsizeof(x)

28

In [17]:
x = 123414141414141341 ** 1000

In [18]:
sys.getsizeof(x)

7596

# NumPy

NumPy provides us with a data structure: NumPy ndarray -- n-dimensional array.

In [19]:
import numpy as np

In [20]:
# don't use np.ndarray!

a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
type(a)

numpy.ndarray

In [22]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
# can we try some list things?

a[0]

10

In [24]:
a[1]

20

In [25]:
a[-1]

90

In [26]:
a[-2]

80

In [27]:
# slice
a[4:7]

array([50, 60, 70])

In [28]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
mylist = [10, 20, 30]
mylist + mylist

[10, 20, 30, 10, 20, 30]

In [30]:
# add a NumPy array to another array
a + a

array([ 20,  40,  60,  80, 100, 120, 140, 160, 180])

In [31]:
b = np.array([100, 200])

a + b

ValueError: operands could not be broadcast together with shapes (9,) (2,) 

 # Another few ways to create arrays
 


In [32]:
# we could do this...
a = np.array(range(10, 20))
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
# ... but instead, we should do this:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
# get a bunch of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
# get a bunch of zeroes
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
# what about random numbers?
np.random.seed(0)
np.random.randint(0, 100, 5)   # 5 numbers from 0-100

array([44, 47, 64, 67, 67])

In [38]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the `~numpy.random.Generator.randint`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to

In [39]:
# what about random floats?

np.random.rand(10)   # how many numbers

array([0.84725174, 0.6235637 , 0.38438171, 0.29753461, 0.05671298,
       0.27265629, 0.47766512, 0.81216873, 0.47997717, 0.3927848 ])

In [40]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
# I want index 3
a[3]

13

In [42]:
# I want index 5
a[5]

15

In [44]:
# I want indexes 3 and 5 -- fancy indexing
a[ [3,5] ]

array([13, 15])