# Agenda

1. `nan`
2. 2D arrays and shapes
3. sorting
4. Pandas

In [2]:
import numpy as np


In [3]:
a = np.array([10, 20, 30, 40, 50])
a.dtype

dtype('int64')

In [4]:
a[2] = 12.34
a

array([10, 20, 12, 40, 50])

In [5]:
a = np.array([10, 20, 30, 40, 50], dtype=np.float64)
a.dtype

dtype('float64')

In [6]:
a[2] = 12.34
a

array([10.  , 20.  , 12.34, 40.  , 50.  ])

In [12]:
a = np.array([10, 20, 30, 40, 50])
a.dtype

dtype('int64')

In [13]:
a[2] = '123'

In [14]:
a

array([ 10,  20, 123,  40,  50])

In [15]:
a.dtype

dtype('int64')

In [16]:
a[3] = 98.76
a.dtype

dtype('int64')

In [10]:
a[3] = 'hello'

ValueError: invalid literal for int() with base 10: 'hello'

In [11]:
a.dtype

dtype('int64')

In [17]:
a = np.array('hello out there'.split())

In [18]:
a

array(['hello', 'out', 'there'], dtype='<U5')

In [19]:
a[0] = 'xyz'
a

array(['xyz', 'out', 'there'], dtype='<U5')

In [20]:
a[1] = 'hijklmnop'

In [21]:
a

array(['xyz', 'hijkl', 'there'], dtype='<U5')

In [23]:
a = a.astype('<U30')
a

array(['xyz', 'hijkl', 'there'], dtype='<U30')

In [24]:
a[1] = 'rstuvwxyz'
a

array(['xyz', 'rstuvwxyz', 'there'], dtype='<U30')

In [25]:
a = np.array([{'a':10, 'b':20}])

In [26]:
a

array([{'a': 10, 'b': 20}], dtype=object)

In [27]:
a = np.array([27, 26, 27, 26, 27])
a.mean()

26.6

In [28]:
# what if we have a problem getting a reading?
a = np.array([27, 26, 0, 26, 27])
a.mean()

21.2

# `nan` -- not a number

`nan` allows us to have numbers but know that they aren't accurate/real.

In [29]:
np.nan

nan

In [30]:
type(np.nan)

float

In [31]:
np.nan == 0

False

In [32]:
np.nan == np.nan

False

In [33]:
a = np.array([10, 20, 30, np.nan, 50, 60])
a

array([10., 20., 30., nan, 50., 60.])

In [34]:
a.dtype

dtype('float64')

In [35]:
a.mean()

nan

In [37]:
# option 1: find nan, remove it, and calculate with the rest
# this doesn't work...

a[a != np.nan].mean()

nan

In [38]:
# use np.isnan, which returns True for nan

np.isnan(a)

array([False, False, False,  True, False, False])

In [41]:
# use ~ to flip the logic
a[~np.isnan(a)].mean()

34.0

In [42]:
a = np.array([10, 20, 30])
a/0

/var/folders/d9/v8tsklln4477fll05wkgcpth0000gn/T/ipykernel_60061/3888640601.py:2: RuntimeWarning: divide by zero encountered in divide
  a/0


array([inf, inf, inf])

In [43]:
type(np.inf)

float

In [44]:
np.inf == np.inf

True

In [45]:
a

array([10, 20, 30])

In [46]:
a = np.array([10, 20, 30, np.nan, np.nan, 50, 60])
a

array([10., 20., 30., nan, nan, 50., 60.])

In [47]:
a.size

7

In [48]:
a.isnan()

AttributeError: 'numpy.ndarray' object has no attribute 'isnan'

In [49]:
np.isnan(a).sum()

2

In [50]:
np.count_nonzero(a)

7

In [51]:
a

array([10., 20., 30., nan, nan, 50., 60.])

In [54]:
# another technique: replace nan with something

a[np.isnan(a)] = 999

In [55]:
a

array([ 10.,  20.,  30., 999., 999.,  50.,  60.])

In [57]:
# similiar: replace nan with the mean

a = np.array([10., 20., 30., np.nan, np.nan, 50., 60.])

# Exercise: Working with `nan`

1. Define a NumPy array with 20 integers between 0-1,000.
2. Change all even numbers to `nan`.
3. Calculate the mean of the numbers that remained.
4. Replace all `nan` values with the non-`nan` mean.

In [58]:
np.random.seed(0)
a = np.random.randint(0, 1000, 20)
a

array([684, 559, 629, 192, 835, 763, 707, 359,   9, 723, 277, 754, 804,
       599,  70, 472, 600, 396, 314, 705])

In [62]:
a = a.astype(np.float64)
a

array([684., 559., 629., 192., 835., 763., 707., 359.,   9., 723., 277.,
       754., 804., 599.,  70., 472., 600., 396., 314., 705.])

In [63]:
# find the even numbers
a[a % 2 == 0] = np.nan

In [64]:
a

array([ nan, 559., 629.,  nan, 835., 763., 707., 359.,   9., 723., 277.,
        nan,  nan, 599.,  nan,  nan,  nan,  nan,  nan, 705.])

In [70]:
# find the mean of these numbers, and assign to the nans

a[np.isnan(a)] = a[~np.isnan(a)].mean()

In [71]:
a

array([560.45454545, 559.        , 629.        , 560.45454545,
       835.        , 763.        , 707.        , 359.        ,
         9.        , 723.        , 277.        , 560.45454545,
       560.45454545, 599.        , 560.45454545, 560.45454545,
       560.45454545, 560.45454545, 560.45454545, 705.        ])

In [73]:
np.nanmean(a)

560.4545454545455

In [75]:
a = np.array([10, 20, 30, np.nan, 40, np.nan])
a

array([10., 20., 30., nan, 40., nan])

In [76]:
np.nan_to_num(a)

array([10., 20., 30.,  0., 40.,  0.])

In [77]:
np.nan_to_num(a, nan=999)

array([ 10.,  20.,  30., 999.,  40., 999.])

In [78]:
np.nan_to_num?

In [80]:
a.astype(float).dtype

dtype('float64')

In [81]:
a.astype(int).dtype

/var/folders/d9/v8tsklln4477fll05wkgcpth0000gn/T/ipykernel_60061/911352652.py:1: RuntimeWarning: invalid value encountered in cast
  a.astype(int).dtype


dtype('int64')

In [82]:
a

array([10., 20., 30., nan, 40., nan])

In [83]:
a.astype('float64')

array([10., 20., 30., nan, 40., nan])

# 2D arrays

NumPy arrays are actually "ndarray" -- n-dimensional arrays. 

I can use a list of lists to create a 2D array.

In [85]:
a = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
             [90, 100, 110, 120]])
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [86]:
a[0] 

array([10, 20, 30, 40])

In [87]:
a[0] + 5

array([15, 25, 35, 45])

In [88]:
# what happens with broadcasting on the whole 2D array?
a + 5

array([[ 15,  25,  35,  45],
       [ 55,  65,  75,  85],
       [ 95, 105, 115, 125]])

In [89]:
a.shape

(3, 4)

In [90]:
# how can I change the shape?
# option 1: assign to .shape

a.shape = (2, 6)
a

array([[ 10,  20,  30,  40,  50,  60],
       [ 70,  80,  90, 100, 110, 120]])

In [91]:
a.shape = (12,)   # tuple with one element still needs ,

In [92]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [93]:
a.shape = (3, 4)
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [94]:
a.shape = (3, 5)

ValueError: cannot reshape array of size 12 into shape (3,5)

In [95]:
a.shape = (3, :)

SyntaxError: invalid syntax (1867200925.py, line 1)

In [96]:
# option 2: use the "reshape" method

# 
a.reshape(3, 4)

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [98]:
a.reshape(3, :)

SyntaxError: invalid syntax (1741208929.py, line 1)

In [100]:
# get random numbers

np.random.randint(0, 1000, 12).reshape(3, 4)

array([[115, 976, 755, 709],
       [847, 431, 448, 850],
       [ 99, 984, 177, 755]])

In [101]:
# even better!
np.random.randint(0, 1000, [3,4])

array([[797, 659, 147, 910],
       [423, 288, 961, 265],
       [697, 639, 544, 543]])

In [102]:
np.random.seed(0)
a = np.random.randint(0, 1000, [5, 6])
a

array([[684, 559, 629, 192, 835, 763],
       [707, 359,   9, 723, 277, 754],
       [804, 599,  70, 472, 600, 396],
       [314, 705, 486, 551,  87, 174],
       [600, 849, 677, 537, 845,  72]])

In [103]:
a[1]

array([707, 359,   9, 723, 277, 754])

In [104]:
a[3]

array([314, 705, 486, 551,  87, 174])

In [105]:
# what if I want both index 1 and 3?
# fancy indexing!
a[ [1,3] ]

array([[707, 359,   9, 723, 277, 754],
       [314, 705, 486, 551,  87, 174]])

In [106]:
# using a slice is a bit different...
a[1:3]   # from 1, up to and not including 3

array([[707, 359,   9, 723, 277, 754],
       [804, 599,  70, 472, 600, 396]])

In [107]:
a[1:5:2]

array([[707, 359,   9, 723, 277, 754],
       [314, 705, 486, 551,  87, 174]])

In [108]:
a

array([[684, 559, 629, 192, 835, 763],
       [707, 359,   9, 723, 277, 754],
       [804, 599,  70, 472, 600, 396],
       [314, 705, 486, 551,  87, 174],
       [600, 849, 677, 537, 845,  72]])

In [110]:
# what if I want from row index 2, and column index 4

a[2][4]

600

In [113]:
# better!
a[2,4]   # I'm really passing a[(2,4)]

600

In [114]:
# what if I want a column?
# we want column index 3

a[:, 3]

array([192, 723, 472, 551, 537])

In [115]:
a

array([[684, 559, 629, 192, 835, 763],
       [707, 359,   9, 723, 277, 754],
       [804, 599,  70, 472, 600, 396],
       [314, 705, 486, 551,  87, 174],
       [600, 849, 677, 537, 845,  72]])

In [116]:
# rows: from 2, until (not including) 4
# columns: 3

a[2:4, 3]

array([472, 551])

In [117]:
# we can slice the columns, too!
# rows: all
# columns: 1-4
a[:, 1:5]

array([[559, 629, 192, 835],
       [359,   9, 723, 277],
       [599,  70, 472, 600],
       [705, 486, 551,  87],
       [849, 677, 537, 845]])

In [118]:
# we can also use lists for fancy indexing!
# rows: 1,2
# columns: 3
a[[1,2], 3]

array([723, 472])

In [119]:
# rows: 3
# columns: 2, 4

a[3, [2,4]]

array([486,  87])

In [121]:
# check this out...
# if you use lists for both, then it creates coordinates
a[[1,2], [3,4]]    # a[1,3] and a[2,4]

array([723, 600])

In [122]:
a[1:3, 3:5]

array([[723, 277],
       [472, 600]])

In [123]:
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [124]:
a.shape

(5,)

In [126]:
a = a.reshape(1,5)
a.shape

(1, 5)

In [127]:
a

array([[10, 20, 30, 40, 50]])

In [128]:
a = np.random.randint(0, 1000, [3,4])
a

array([[777, 916, 115, 976],
       [755, 709, 847, 431],
       [448, 850,  99, 984]])

In [129]:
a.sum()

7907

In [130]:
a.sum(axis=0)

array([1980, 2475, 1061, 2391])

In [131]:
a.sum(axis=1)

array([2784, 2742, 2381])