# Agenda

1. Extension dtypes
2. Files
    - CSV
    - JSON
    - Excel
    - Other formats

In [2]:
import numpy as np
a = np.array([10, 20, 30, 40, 50])
a

array([10, 20, 30, 40, 50])

In [3]:
a.dtype

dtype('int64')

In [4]:
a[2] = 2345
a

array([  10,   20, 2345,   40,   50])

In [5]:
a[2] = 23.45
a

array([10, 20, 23, 40, 50])

In [6]:
a[3] = '123'
a

array([ 10,  20,  23, 123,  50])

In [7]:
a[4] = np.nan

ValueError: cannot convert float NaN to integer

In [9]:
import pandas as pd
from pandas import Series, DataFrame

In [10]:
s = Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [11]:
s.loc[2] = 2345
s

0      10
1      20
2    2345
3      40
4      50
dtype: int64

In [12]:
s.loc[2] = 23.45


In [13]:
s

0    10.00
1    20.00
2    23.45
3    40.00
4    50.00
dtype: float64

In [14]:
s = Series([10, 20, 30, 40, 50])
s.loc[2] = np.nan

In [15]:
s

0    10.0
1    20.0
2     NaN
3    40.0
4    50.0
dtype: float64

In [16]:
s = Series('this is a test'.split())
s

0    this
1      is
2       a
3    test
dtype: object